# Dependencies
gems:                [jekyll-paginate]
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Software Engineering Management Blog
tagline:          'A Blog for Software Engineering Managers'
description:      'Many management blogs focus on soft skills. This blog is about hard skills! Measurement, indicators, approaches, etc., for Software Engineering Management.'
url:              https://pplupo.github.io/
baseurl:          /

author:
  name:           'Peter P. Lupo'
  url:            https://www.pplupo.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pplupo/blog
